version: "3"

services:
  web:
    container_name: web
    image: ifpb/php:7.3-apache-pdo
    build: .
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: example
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    networks:
      - app-tier
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer:4.7.5
    restart: always
    networks:
      - app-tier
    ports:
      - 8081:8080
    depends_on:
      - mysql

networks:
  app-tier:
    driver: bridge
